/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(basis_change.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a88b812d1f45527c1655776bde34f184)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/basis_change.h>
// pydoc.h is automatically generated in the build directory
#include <basis_change_pydoc.h>

void bind_basis_change(py::module& m)
{

    using basis_change = ::gr::analog::basis_change;


    py::class_<basis_change,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<basis_change>>(m, "basis_change", D(basis_change))

        .def(py::init(&basis_change::make),
             py::arg("vlen"),
             py::arg("circ_to_lin"),
             D(basis_change, make))


        ;
}
